spring:
  application:
    name: gym-backend
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Gym@2025}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}

cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173,http://127.0.0.1:5173}

cloudinary:
  url: ${CLOUDINARY_URL:cloudinary://241373855128489:-3GUz1vsWQu-rxIBxreh_5qGCfc@deq0lcxzc}
