package com.example.gymbackend.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * Proposals generated by the Gemini AI marketing agent.
 * Maps to the `propuestas_marketing` table created via schema_supabase.sql.
 */
@Entity
@Table(name = "propuestas_marketing")
@Getter
@Setter
public class MarketingProposal {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "titulo", nullable = false)
    private String titulo;

    @Column(name = "tipo", nullable = false)
    private String tipo; // 'promocion', 'campaña_marketing', 'consejo_retencion', 'estrategia'

    @Column(name = "descripcion", columnDefinition = "TEXT")
    private String descripcion;

    @Column(name = "acciones", columnDefinition = "TEXT")
    private String acciones;

    @Column(name = "fecha_generacion")
    private LocalDateTime fechaGeneracion;

    @Column(name = "estado")
    private String estado = "pendiente"; // 'pendiente', 'en_progreso', 'completada', 'descartada'

    @Column(name = "resultado", columnDefinition = "TEXT")
    private String resultado;

    @Column(name = "created_at")
    private LocalDateTime createdAt;
}
